services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/srv/app.local/
    depends_on:
      - php
    networks:
      - app-network
  php:
    build: ./services/php
    container_name: php
    volumes:
      - ./app:/srv/app.local/
    working_dir: /srv/app.local/
    networks:
      - app-network
    command: sh -c "php artisan migrate & php artisan queue:work --queue=telegram & php-fpm" #& php artisan serve --host=0.0.0.0 --port=8000"
  postgres:
    image: postgres:17.4
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./services/postgres/data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
